FROM alpine:3

ARG TARGETARCH

ENV AZURE_TENANT_ID=""
ENV AZURE_CLIENT_ID=""
ENV AZURE_CLIENT_SECRET=""
ENV BOOKSTACK_TOKEN_ID=""
ENV BOOKSTACK_TOKEN_SECRET=""
ENV BOOKSTACK_PAGE_ID=""
ENV BOOKSTACK_URL=""

COPY ./build/$TARGETARCH /m365-mailbox-report

ENTRYPOINT [ "/m365-mailbox-report" ]
